moovi-web/src/main/java/lab/moovi/web/rest/dto/CinemaDTO.java
package lab.moovi.web.rest.dto;

public class CinemaDTO {

    int id;

    String name;

    String logo;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getLogo() {
        return logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }
}

moovi-web/src/main/java/lab/moovi/web/faces/MooviBean.java
package lab.moovi.web.faces;

import lab.moovi.model.Cinema;
import lab.moovi.model.Movie;
import lab.moovi.service.MoviService;
import lab.moovi.service.impl.MoviServiceImpl;

import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import java.util.Map;
import java.util.Set;

@ManagedBean(name="mooviBean")
public class MooviBean {

    @Inject
    MoviService service;

    public Set<Cinema> getAllCinemas(){
        return service.getAllCinemas();
    }

    public Set<Movie> getMovies(){

        String cinema = getParameter("cinema");

        if(cinema!=null){
            int cinemaId = Integer.parseInt(cinema);
            Cinema c = service.getCinemaById(cinemaId);
            return service.getMoviesInCinema(c);
        }

        return service.getAllMovies();
    }

    private String getParameter(String name) {
        Map<String, String> params =
        FacesContext.
                getCurrentInstance().
                getExternalContext().
                getRequestParameterMap();
        return params.get(name);
    }

}

moovi-web/src/main/java/lab/moovi/web/servlet/CinemaServlet.java
package lab.moovi.web.servlet;

import lab.moovi.model.Cinema;
import lab.moovi.model.Movie;

import lab.moovi.service.MoviService;
import lab.moovi.service.impl.MoviServiceImpl;

import javax.inject.Inject;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.Set;

@WebServlet("/cinemas")
public class CinemaServlet extends HttpServlet {

    @Inject
    MoviService service;

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {

        String movie = req.getParameter("movie");

        Set<Cinema> cinemas;
        String title;

        if(movie!=null){
            int movieId = Integer.parseInt(movie);
            Movie m = service.getMovieById(movieId);
            title = "List of cinemas playing " + m.getTitle();
            cinemas = service.getCinemasByMovie(m);
        } else {
            title = "List of cinemas";
            cinemas = service.getAllCinemas();
        }

        req.setAttribute("title", title);
        req.setAttribute("cinemas", cinemas);
        req.getRequestDispatcher("/WEB-INF/jsp/cinemas.jsp").forward(req, resp);

    }
}

moovi-web/src/main/java/lab/moovi/web/servlet/MovieServlet.java
package lab.moovi.web.servlet;

import lab.moovi.model.Cinema;
import lab.moovi.model.Movie;
import lab.moovi.service.MoviService;
import lab.moovi.service.impl.MoviServiceImpl;
import org.apache.commons.lang3.math.NumberUtils;


import javax.inject.Inject;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.HashSet;
import java.util.Set;

@WebServlet("/movies")
public class MovieServlet extends HttpServlet {

    @Inject
    MoviService service;

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {

        // /movies?cinema=999&param2=abc
        String cinema = req.getParameter("cinema");

        Set<Movie> movies;
        String title;
        if(cinema!=null){

            boolean parsable = NumberUtils.isParsable(cinema);
            if(parsable) {
                int cinemaId = Integer.parseInt(cinema);

                Cinema c = service.getCinemaById(cinemaId);
                if (c != null) {
                    title = "List of cinemas in " + c.getName();
                    movies = service.getMoviesInCinema(c);
                } else {
                    title = "Missing cinema of id " + cinemaId;
                    movies = new HashSet();
                }
            } else {
                title = "Non parseable id provided: " + cinema;
                movies = new HashSet<>();
            }
        } else {
            movies = service.getAllMovies();
            title = "List of movies";
        }
        req.setAttribute("movies", movies);
        req.setAttribute("title", title);

        req.getRequestDispatcher("/WEB-INF/jsp/movies.jsp").forward(req, resp);
    }
}

moovi-web/src/main/webapp/WEB-INF/jsp/cinemas.jsp
<%@ page import="lab.moovi.model.Cinema" %>
<%@ page import="java.util.Set" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<jsp:include page="header.jsp"/>

        <table>
            <tr>
                <th>Logo</th>
                <th>Name</th>
                <th>Movies</th>
            </tr>
            <c:forEach items="${requestScope.cinemas}" var="cinema">
                <tr>
                    <td><img src="${cinema.logo}"></td>
                    <td>${cinema.name}</td>
                    <td><a href='<c:url value="/movies?cinema=${cinema.id}"/>'>show</a></td>
                </tr>
            </c:forEach>

        </table>

<jsp:include page="footer.jsp"/>

moovi-web/src/main/webapp/WEB-INF/jsp/footer.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

    </section>

</body>
</html>

moovi-web/src/main/webapp/WEB-INF/jsp/header.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<html>
<head>
    <title>Moovi</title>
    <link rel="stylesheet" href='<c:url value="/css/style.css"/>'/>
    <link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet"/>
</head>
<body>
    <header>
        <h1>Moovi</h1>
        <h2>${requestScope.title}</h2>
    </header>


    <section>

moovi-web/src/main/webapp/WEB-INF/jsp/movies.jsp
<%@ page import="lab.moovi.model.Cinema" %>
<%@ page import="java.util.Set" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<jsp:include page="header.jsp"/>

        <table>
            <tr>
                <th>Poster</th>
                <th>Title</th>
                <th>Rating</th>
                <th>Director</th>
                <th>Cinemas</th>
            </tr>
            <c:forEach items="${requestScope.movies}" var="movie">
                <tr>
                    <td><img src="${movie.poster}"></td>
                    <td><c:out value="${movie.title}"/></td>
                    <td>${movie.rating}</td>
                    <td>${movie.director.lastName} ${movie.director.firstName}</td>
                    <td><a href='<c:url value="/cinemas?movie=${movie.id}"/>'>show</a></td>
                </tr>
            </c:forEach>

        </table>

<jsp:include page="footer.jsp"/>

moovi-web/src/main/webapp/jsf/cinemas.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">


<h:body>

    <ui:composition template="template.xhtml">
        <ui:define name="title">List of cinemas</ui:define>
        <ui:define name="content">
            <h:dataTable var="cinema" value="#{mooviBean.allCinemas}">
                <h:column>
                    <f:facet name="header">#{msg['label.logo']}</f:facet>
                    <h:graphicImage value="#{cinema.logo}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">#{msg['label.name']}</f:facet>
                    #{cinema.name}
                </h:column>
                <h:column>
                    <f:facet name="header">#{msg['label.movies']}</f:facet>
                    <h:link value="show" outcome="movies">
                        <f:param name="cinema" value="#{cinema.id}"/>
                    </h:link>
                </h:column>
            </h:dataTable>
        </ui:define>
    </ui:composition>

</h:body>


</html>

moovi-web/src/main/webapp/jsf/movies.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">


<h:body>

    <ui:composition template="template.xhtml">
        <ui:define name="title">List of movies</ui:define>
        <ui:define name="content">
            <h:dataTable var="movie" value="#{mooviBean.movies}">
                <h:column>
                    <f:facet name="header">Poster</f:facet>
                    <h:graphicImage value="#{movie.poster}"/>
                </h:column>
                <h:column>
                    <f:facet name="header">Title</f:facet>
                    #{movie.title}
                </h:column>
                <h:column>
                    <f:facet name="header">Rating</f:facet>
                    #{movie.rating}
                </h:column>
                <h:column>
                    <f:facet name="header">Director</f:facet>
                    #{movie.director.lastName}
                </h:column>
            </h:dataTable>
        </ui:define>
    </ui:composition>

</h:body>


</html>

moovi-web/src/main/webapp/jsf/template.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

<h:head>
    <title>Moovi</title>
    <h:outputStylesheet library="css" name="style.css"></h:outputStylesheet>
    <link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet"/>
</h:head>
<h:body>
    <header>
        <h1>Moovi JSF</h1>
        <h2><ui:insert name="title">No title</ui:insert></h2>
    </header>
    <section>
       <ui:insert name="content">No content</ui:insert>
    </section>

</h:body>


</html>